version: '3.8'

services:
  web:
    restart: always
    build: .
    command: >
      sh -c "cd /app/zadacnhic/
      && python manage.py migrate --noinput
      && python manage.py runserver 0.0.0.0:8000"
    expose:
      - 8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres_volume:
