# Generated by Django 4.2.2 on 2023-08-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='user telegram id'),
        ),
    ]
