# Generated by Django 4.2.4 on 2023-09-03 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuserverifycode',
            name='telegram_code',
            field=models.CharField(blank=True, max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='6 digits code'),
        ),
    ]
