# Generated by Django 4.2.4 on 2023-08-30 14:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_settings_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUserVerifyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_code', models.CharField(blank=True, max_length=4, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='4 digits code')),
                ('settings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_verify_code', to='accounts.settings')),
            ],
            options={
                'verbose_name': 'telegram code',
                'verbose_name_plural': 'telegram codes',
            },
        ),
    ]
