# Generated by Django 4.2.2 on 2023-08-13 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'settings', 'verbose_name_plural': 'settings'},
        ),
    ]
