# Generated by Django 4.2.2 on 2023-08-13 23:21

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_settings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='currency',
            field=models.CharField(blank=True, choices=[('R', 'Ruble'), ('D', 'Dollar'), ('E', 'Euro')], default=accounts.models.SettingsСurrencyChoices.get_default, max_length=2, verbose_name='currency'),
        ),
    ]
