# Generated by Django 4.2.2 on 2023-08-19 22:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='transaction amount')),
                ('name', models.CharField(max_length=50, verbose_name='transaction name')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='transaction description')),
                ('cost_accounting_date', models.DateField(auto_now_add=True, verbose_name='cost accounting date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='transaction modified date')),
                ('transaction_date', models.DateField(verbose_name='date of transaction')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.category', verbose_name='transaction category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='transaction author')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ('-transaction_date',),
            },
        ),
    ]
