# Generated by Django 4.2.2 on 2023-08-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(verbose_name='transaction amount'),
        ),
    ]
