# Generated by Django 4.2.2 on 2023-08-15 18:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='expense amount')),
                ('name', models.CharField(max_length=50, verbose_name='expense name')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='expense description')),
                ('cost_accounting_date', models.DateField(auto_now_add=True, verbose_name='cost accounting date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='expense modified date')),
                ('expense_date', models.DateField(verbose_name='date of expense')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.category', verbose_name='expense category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='expense author')),
            ],
            options={
                'verbose_name': 'expense',
                'verbose_name_plural': 'expenses',
                'ordering': ('-expense_date',),
            },
        ),
    ]
