# Generated by Django 4.2.2 on 2023-08-13 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_category_name_alter_category_slug_expense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('-expense_date',), 'verbose_name': 'expense', 'verbose_name_plural': 'expenses'},
        ),
    ]
