name: flake8 lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install isort flake8 flake8-django flake8-multiline-containers flake8-docstrings flake8-quotes pep8-naming
      - name: Lint with flake8
        run: |
          flake8 --exclude migrations --max-line-length 100 money_tracker/
      - name: Lint with isort
        run: isort -qc .